### ISSUE TITLE
Odd Left Border for Offers and Footer Panes on MD to XS

### ISSUE THREAD

**Issue by zent-lim** [usbong/UsbongStore#94]
Hi Mike,

(1) The commit below seem to have damaged layout:

      caa30b3d5ad0a2184f04c1d9a1c7d6113da3d4d3

(2) There is now a thin left border like margin on the footer and the offers pane.

![screenshot-2018-5-4 usbong store 2](https://user-images.githubusercontent.com/8021327/39609760-dd375a8e-4f7d-11e8-995d-a6e7165c74a7.png)

(3) I think the version I wrote looks better.

      Are you sure you'd like to maintain this look?

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for sending me your findings.

The thin left border-like margin you mention is likely related to the style used in the right panel and the footer.

Would you be able to put in the time to figure out how to resolve this?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I recommend to rollback to the version i wrote instead of giving time to
investigate this concern.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

If we do a rollback, the issue we have with the categories not in only 1 row, etc, i.e. https://github.com/usbong/UsbongStore/issues/90, will not have yet been resolved.

Let me keep this issue open for now.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) My version is better base. Two tickets will be closed if we use my
version as base.

(2) Regarding the categories as one row, i recommend my version of two rows.

(3) but we can use my version as base and  contain it in one row instead.

Several problems will persists though:
(1) it s going to look bad on xs
(2) smaller versions of lg screen will still display it in two rows
(3) when u have more categories, it will use more than two rows
(4) md screen lower will use more than one row

Pls advise me when i can start editing codes again.

Morning!

On May 5, 2018 10:41 AM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
Thank you for the reply.

If we do a rollback, the issue we have with the categories not in only 1
row, etc, i.e. #90 <https://github.com/usbong/UsbongStore/issues/90>, will
not have yet been resolved.

Let me keep this issue open for now.

Thank you.

Peace,
Mike

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/94#issuecomment-386773571>,
or mute the thread

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Can you send me a screen shot and a pull request of this?
"(3) but we can use my version as base and contain it in one row instead."

This should resolve the the full screen  issue in https://github.com/usbong/UsbongStore/issues/90.

Regarding the several problems that you say will persist, here are my responses.
(1) Can you clarify what you mean? Perhaps, you can show me a screenshot?
(2) OK.
(3) OK.
(4) OK.

Please start editing code again.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

On Sat, May 5, 2018 at 8:14 PM, Masarap Mabuhay <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the reply.
>
> Can you send me a screen shot and a pull request of this?
> "(3) but we can use my version as base and contain it in one row instead."
>
I already did.

"My version" refers to old code I pushed.

Please see this thread for your screen shot and pull request.

Email: Mobile Responsive Beverage Page
Date: April 22
Message:
      "Good Day Mike,

      Please see Milestones 1 to 4 below:

      (1) Mobile Responsiveness of Content and Right Side Bar of Beverage
Page
      (2) Fix Unnecessary Horizontal Right Scroll of Beverage Page
      (3) Mobile Responsiveness of Footer of Beverage Page
      (4) Mobile Responsiveness of Search Header of Beverage Page"

I've sent you screen shots from xs to lg screens on different operating
modes.

This should resolve the the full screen issue in #90
> <https://github.com/usbong/UsbongStore/issues/90>.
>
> Regarding the several problems that you say will persist, here are my
> responses.
> (1) Can you clarify what you mean? Perhaps, you can show me a screenshot?
>
I already did.

Please see the first message in this thread:
https://github.com/usbong/UsbongStore/issues/92

> (2) OK.
> (3) OK.
> (4) OK.
>
> Please start editing code again.
>
I already did. my latest update was on the ticket below an hour after you
said I could start writing code again:
https://github.com/usbong/UsbongStore/issues/90

Have a good day ahead!

**Comment by zent-lim** [comment]
Hi Mike,

Fixing this ticket is outside the agreed scope of my deliverables as the footer was already fixed (and later damaged) on my commit on april 22.

commit ba60676e7b057ce9a0303aef7f2d881e33d3888d
Date: Sun Apr 22 21:08:08 2018 +0800
Note: Fixed mobile responsiveness of b/beverages.

If however we finish the other concerns early, I will be happy to help re-fix this issue.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

OK. Please send me the pull requests.

I will reverify if your newest code commit 
really did resolve the issue with more than 
1 row for categories when in full screen.

I understand that for this, 
you did not use `container-fluid`.

Please correct me if my 
understanding is wrong.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

There is no new pull request.

(1) I recommended you to have more than one row for categories on lg screen.

(2) You then updated code to fit it in one row which in turn damaged the layout.

This ticket is no longer in the scope of my deliverables. But if we finish issue 90 early, I would be glad to help out.

Good morning.

**Comment by zent-lim** [comment]
Hi Mike,

Apologies. Wrong comment. This ticket is for the damaged footer.

The categories header is for ticket 93.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

OK. In that case, 
this ticket/issue 
isn't yet resolved.

Please correct me if my 
understanding is wrong.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) Yes. The ticket is left open.

(2) This ticket is outside the scope of our agreement.

      I have fixed the footer to be mobile responsive.

      The damage was introduced after your code update.

(3) I have assigned the ticket to you.

Good morning!

**Comment by zent-lim** [comment]
Okly dokly!

Verifying. :)

**Comment by zent-lim** [comment]
Hi Mike,

Looks clean!

This ticket is closed.

A new problem came up though. I filed new ticket below:
https://github.com/usbong/UsbongStore/issues/96

Morning!
